# Site settings
title: Catálogo de Patrimonio de Campo de Criptana
header-img: img/home-bg.jpg
email: forosocialcriptana@gmail.com
description: "Lugares de interés histórico, artístico, ambiental y etnográfico de Campo de Criptana"
baseurl: ""
url: "http://forosocialcriptana.github.io"
twitter_username: fscriptana
facebook_username:  forosocialcriptana
instagram_username: forosocialcriptana
discus_shortname: forosocialcriptana

# Google Analytics
# To enable google analytics, uncomment below line with a valid Google Tracking ID
# google_tracking_id:

# Build settings
markdown: kramdown
permalink: pretty
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
