# Site settings
title: Catálogo del Patrimonio de Campo de Criptana
header-img: img/home-bg.jpg
email: catalogopatrimoniocriptana@gmail.com
description: "Lugares de interés histórico, artístico, ambiental y etnográfico de Campo de Criptana"
baseurl: ""
url: "https://patrimoniocriptana.github.io/"
twitter_username: patrimocriptana
facebook_username: 1646242979005609
discus_shortname: patrimoniocriptana
email_username: catalogopatrimoniocriptana@gmail.com

# Google Analytics
# To enable google analytics, uncomment below line with a valid Google Tracking ID
# google_tracking_id:

# Build settings
markdown: kramdown
permalink: pretty
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
